version: '3.9'

services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: cloudgames-azurite
    ports:
      - "10000:10000"  # Blob
      - "10001:10001"  # Queue
      - "10002:10002"  # Table
    volumes:
      - azurite_data:/data
    command: azurite --blobHost 0.0.0.0 --queueHost 0.0.0.0 --tableHost 0.0.0.0 --location /data --loose
    restart: unless-stopped

  # users:
  #   build:
  #     context: ../services/CloudGames.Users
  #     dockerfile: Dockerfile
  #   container_name: cloudgames-users
  #   depends_on:
  #     - azurite
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - Jwt__Secret=0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef
  #     - Jwt__Issuer=CloudGames.Users
  #     - Jwt__Audience=CloudGames.Clients
  #     - ConnectionStrings__Storage=UseDevelopmentStorage=true
  #     # NOTE: The APIs currently use SQL Server; provide a SQL Server connection string if running in containers
  #     # - ConnectionStrings__UsersDb=Server=sqlserver,1433;Database=CloudGames.Users;User Id=sa;Password=Your_password123;TrustServerCertificate=True
  #   ports:
  #     - "5001:80"
  #   restart: unless-stopped

  # games:
  #   build:
  #     context: ../services/CloudGames.Games
  #     dockerfile: Dockerfile
  #   container_name: cloudgames-games
  #   depends_on:
  #     - azurite
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - Jwt__Secret=0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef
  #     - Jwt__Issuer=CloudGames.Users
  #     - Jwt__Audience=CloudGames.Clients
  #     - ConnectionStrings__Storage=UseDevelopmentStorage=true
  #     # - ConnectionStrings__GamesDb=Server=sqlserver,1433;Database=CloudGames.Games;User Id=sa;Password=Your_password123;TrustServerCertificate=True
  #     # Optional search config if you want ACS live calls during local container run
  #     # - Search__Endpoint=https://<your-search>.search.windows.net
  #     # - Search__ApiKey=<admin-key>
  #     # - Search__IndexName=games
  #   ports:
  #     - "5002:80"
  #   restart: unless-stopped

  # payments:
  #   build:
  #     context: ../services/CloudGames.Payments
  #     dockerfile: Dockerfile
  #   container_name: cloudgames-payments
  #   depends_on:
  #     - azurite
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - Jwt__Secret=0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef
  #     - Jwt__Issuer=CloudGames.Users
  #     - Jwt__Audience=CloudGames.Clients
  #     - ConnectionStrings__Storage=UseDevelopmentStorage=true
  #     # - ConnectionStrings__PaymentsDb=Server=sqlserver,1433;Database=CloudGames.Payments;User Id=sa;Password=Your_password123;TrustServerCertificate=True
  #   ports:
  #     - "5003:80"
  #   restart: unless-stopped

volumes:
  azurite_data:
    driver: local
